sudo: required
services:
- docker
addons:
  apt:
    packages:
    - docker-ce
    - enchant
language: python
python:
- '3.5'
env:
  matrix:
  - CI_PATTERN=''
  - CI_PATTERN=tests/test_dcos_artifact_info.py::TestOSS::test_master
  - CI_PATTERN=tests/test_dcos_artifact_info.py::TestOSS::test_1_12
  - CI_PATTERN=tests/test_dcos_artifact_info.py::TestOSS::test_1_11
  - CI_PATTERN=tests/test_dcos_artifact_info.py::TestOSS::test_1_10
  - CI_PATTERN=tests/test_dcos_artifact_info.py::TestOSS::test_1_9
  - CI_PATTERN=tests/test_dcos_artifact_info.py::TestEnterprise::test_master
  - CI_PATTERN=tests/test_dcos_artifact_info.py::TestEnterprise::test_1_12
  - CI_PATTERN=tests/test_dcos_artifact_info.py::TestEnterprise::test_1_11
  - CI_PATTERN=tests/test_dcos_artifact_info.py::TestEnterprise::test_1_10
  - CI_PATTERN=tests/test_dcos_artifact_info.py::TestEnterprise::test_1_9
before_install:
- echo $LICENSE_KEY_CONTENTS > /tmp/license-key.txt
- travis_retry pip install --upgrade pip setuptools codecov
install:
- travis_retry pip install --upgrade --editable .[dev]
cache: pip
before_script:
- travis_retry python admin/download_artifacts.py
script:
- python admin/run_script.py
after_success:
- codecov
