sudo: false
addons:
  apt:
    packages:
    - enchant
language: python
python:
- '3.5'
env:
  matrix:
  - CI_PATTERN=''
  - CI_PATTERN=tests/test_dcos_artifact_info.py::TestOSS::test_master
  - CI_PATTERN=tests/test_dcos_artifact_info.py::TestOSS::test_1_12
  - CI_PATTERN=tests/test_dcos_artifact_info.py::TestOSS::test_1_11
  - CI_PATTERN=tests/test_dcos_artifact_info.py::TestOSS::test_1_10
  - CI_PATTERN=tests/test_dcos_artifact_info.py::TestOSS::test_1_9
  - CI_PATTERN=tests/test_dcos_artifact_info.py::TestEnterprise::test_master
  - CI_PATTERN=tests/test_dcos_artifact_info.py::TestEnterprise::test_1_12
  - CI_PATTERN=tests/test_dcos_artifact_info.py::TestEnterprise::test_1_11
  - CI_PATTERN=tests/test_dcos_artifact_info.py::TestEnterprise::test_1_10
  - CI_PATTERN=tests/test_dcos_artifact_info.py::TestEnterprise::test_1_9
